name: eda
description: Dart Event-driven architecture (EDA) framework
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  collection: ^1.19.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.7
